//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect.Framework.Reflection {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReflectionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReflectionStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intersect.Framework.Reflection.ReflectionStrings", typeof(ReflectionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create instance of {0}..
        /// </summary>
        internal static string AssemblyExtensions_FailedToCreateInstance {
            get {
                return ResourceManager.GetString("AssemblyExtensions_FailedToCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Found no matching subtype of {0} that can be created..
        /// </summary>
        internal static string AssemblyExtensions_NoMatchingSubtype {
            get {
                return ResourceManager.GetString("AssemblyExtensions_NoMatchingSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected an incomplete type but received {0}..
        /// </summary>
        internal static string ExpectedAnIncompleteTypeButReceivedX {
            get {
                return ResourceManager.GetString("ExpectedAnIncompleteTypeButReceivedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected abstract/interface type, received {0}.
        /// </summary>
        internal static string TypeExtensions_FindConcreteType_ExpectedAbstractOrInterface {
            get {
                return ResourceManager.GetString("TypeExtensions_FindConcreteType_ExpectedAbstractOrInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is not a generic type and does not extend from a generic type..
        /// </summary>
        internal static string TypeExtensions_FindGenericTypeParameters_NotGeneric {
            get {
                return ResourceManager.GetString("TypeExtensions_FindGenericTypeParameters_NotGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not a valid generic type definition: {0}.
        /// </summary>
        internal static string TypeExtensions_FindGenericTypeParameters_NotValidGenericTypeDefinition {
            get {
                return ResourceManager.GetString("TypeExtensions_FindGenericTypeParameters_NotValidGenericTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing embedded resource: &quot;{0}&quot;.
        /// </summary>
        internal static string UnpackEmbeddedFile_MissingManifestResourceInfo {
            get {
                return ResourceManager.GetString("UnpackEmbeddedFile_MissingManifestResourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to open stream for embedded resource: {0}.
        /// </summary>
        internal static string UnpackEmbeddedFile_UnableToOpenStream {
            get {
                return ResourceManager.GetString("UnpackEmbeddedFile_UnableToOpenStream", resourceCulture);
            }
        }
    }
}
